name: Security check with snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    environment:
      name: snyk
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
